/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencentcloudapi.cvm.v20170312.models;

import com.tencentcloudapi.common.AbstractModel;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import java.util.HashMap;

public class CreateDisasterRecoverGroupRequest  extends AbstractModel{

    /**
    * Name of a spread placement group with a length of 1-60 characters.
    */
    @SerializedName("Name")
    @Expose
    private String Name;

    /**
    * Type of spread placement group, value:<br><li>Host: Physical machine<br><li>SW: Switch<br><li>Rack: Rack
    */
    @SerializedName("Type")
    @Expose
    private String Type;

    /**
    * A string to ensure the idempotency of the request, which is generated by customer. Each request shall have a unique string with a maximum of 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be ensured.<br>For more information, please check How to Ensure Idempotency.
    */
    @SerializedName("ClientToken")
    @Expose
    private String ClientToken;

    /**
     * Get name of a spread placement group with a length of 1-60 characters.
     * @return Name Name of a spread placement group with a length of 1-60 characters.
     */
    public String getName() {
        return this.Name;
    }

    /**
     * Set name of a spread placement group with a length of 1-60 characters.
     * @param Name Name of a spread placement group with a length of 1-60 characters.
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    /**
     * Get type of spread placement group, value:<br><li>Host: Physical machine<br><li>SW: Switch<br><li>Rack: Rack
     * Type of spread placement group, value:<br><li>Host: Physical machine<br><li>SW: Switch<br><li>Rack: Rack
     */
    public String getType() {
        return this.Type;
    }

    /**
     * Set type of spread placement group, value:<br><li>Host: Physical machine<br><li>SW: Switch<br><li>Rack: Rack
     * @param Type Type of spread placement group, value:<br><li>Host: Physical machine<br><li>SW: Switch<br><li>Rack: Rack
     */
    public void setType(String Type) {
        this.Type = Type;
    }

    /**
     * Get a string to ensure the idempotency of the request, which is generated by customer. Each request shall have a unique string with a maximum of 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be ensured.<br>For more information, please see How to Ensure Idempotency.
     * @return ClientToken A string to ensure the idempotency of the request, which is generated by customer. Each request shall have a unique string with a maximum of 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be ensured.<br>For more information, please see How to Ensure Idempotency.
     */
    public String getClientToken() {
        return this.ClientToken;
    }

    /**
     * Set a string to ensure the idempotency of the request, which is generated by customer. Each request shall have a unique string with a maximum of 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be ensured.<br>For more information, please see How to Ensure Idempotency.
     * @param ClientToken A string to ensure the idempotency of the request, which is generated by customer. Each request shall have a unique string with a maximum of 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be ensured.<br>For more information, please see How to Ensure Idempotency.
     */
    public void setClientToken(String ClientToken) {
        this.ClientToken = ClientToken;
    }

    /**
     * For internal use only
     */
    public void toMap(HashMap<String, String> map, String prefix) {
        this.setParamSimple(map, prefix + "Name", this.Name);
        this.setParamSimple(map, prefix + "Type", this.Type);
        this.setParamSimple(map, prefix + "ClientToken", this.ClientToken);

    }
}

